### ISSUE TITLE
feature-request : settings page

### ISSUE THREAD

**Issue by defmementomori** [xhiroga/aws-peacock-management-console#13]
### Description:
for more useful , it will be good to access the settings we set before when opening settings page 

### Expected result:
1. set config in settings page
2. colse settings page
3. reopen setting page(with settings info we set before)

**Comment by defmementomori** [comment]
もし良ければPR出してみれればと思います

**Comment by xhiroga** [comment]
@defmementomori 
Thank you for reporting. Could you reproduce it at v1.2?
https://github.com/xhiroga/aws-peacock-management-console/releases/tag/v1.2

**Comment by xhiroga** [comment]
@defmementomori Sorry, I append already builded zip file on above release, 1.2.

**Comment by xhiroga** [comment]
This bug was fixed and no additional error was reported. I close this issue but feel free to report or reopen if something strage!
