### ISSUE TITLE
account alias support

### ISSUE THREAD

**Issue by sogaoh** [xhiroga/aws-peacock-management-console#22]
### Description

v1.3 時点ではアカウントIDでの区別のみに対応されているように感じています。
アカウントエイリアスで区別できるとありがたいです。

### Use Case

ほぼ、アカウントエイリアスを指定してコンソールにログインしています。
（アカウントIDを指定する場合もありますが自分の場合レアケースです）

### Proposed Solution

アカウントID か アカウントエイリアス のいずれかの指定があったときに有効になるとうれしいです。
両方あった場合はアカウントID優先で良いような気がします。

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
@sogaoh   ご提案ありがとうございます！
お気持ちは大変分かるのですが、以下の2点から実装を見送らせて下さい。

1. マネジメントコンソール上でアカウントエイリアスを確実に取得できる見通しが立たない
2. アカウントエイリアスとアカウント名が混同されやすい

(1) について、例えばスイッチロールとAWS SSOを併用するような環境だった場合に、スイッチロールでは色が変わるがSSOでは変わらない、という状況が発生しえます。
(2) について、例えばOrganizationの機能でAWSアカウントを開設した場合など、アカウントエイリアスを設定したつもりがアカウント名しか設定されていない、というケースがありえそうです。そうした場合にこの拡張機能が働かないのでは？とお考えになる方もいらっしゃるかと思いまして。

JSONCフォーマットまたはYAMLでConfigにコメントいただければと思います。
