### ISSUE TITLE
yaml configuration support

### ISSUE THREAD

**Issue by sogaoh** [xhiroga/aws-peacock-management-console#23]
### Description

v1.3 時点ではオプションでの Configuration は json (+アルファ?) 形式での設定が想定されているように感じます。
設定を yaml で行えるようになっていると、コメントが書きやすい・フォーマット(lint)を気にする機会が減る、
と思うので可能であれば yaml 対応いただきたいです。

### Use Case

- Configuration の末尾等にコメントを記述する場合（行頭に書ける json なのも地味に凄い）
- オプションを書き換える時にカンマが残っているかを気にしなくて良くなると思う

### Proposed Solution

- yaml 形式での Configuration 画面が追加であると良さそう
    - json と両方ある場合は json 優先で良いように思います
    
- 現状の Configuration を json か yaml か選択させるようにしてそれに従ってパースする、でも良いかもしれません

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by umireon** [comment]
YAMLパーサーはJSONもパースできるので、コンフィグのパースをJSON.parseからYAMLのライブラリに置き換えるだけでこれは実現できます

**Comment by xhiroga** [comment]
いいですね！
JSONCもパースしてくれるかは確認したいところです。

もしくは変換はユーザーに任せ、URL経由でJSONを読み取るという手も…

**Comment by umireon** [comment]
JSONCのパースはYAMLのライブラリでは無理そうです。

`#`か`-`で始まったらYAML、`/`か`[`で始まったらJSONCとしてパースすればいいんじゃないでしょうか？

**Comment by umireon** [comment]
```
const configListIsYaml = (configList: string) => /^\s*[#-]/.test(configList)
const configListIsJsonc = (configList: string) => /^\s*[\/\[]/.test(configList)

configListIsYaml(configList) ? YAML.parse(configList) :
configListIsJsonc(configList) ? parse(configList) :
JSON.parse(configList)
```

**Comment by xhiroga** [comment]
Now YAML supported!!!
<img width="437" alt="image" src="https://user-images.githubusercontent.com/13391129/170151062-49330a41-c89a-4ceb-9b67-dd6beef5e00d.png">
(Account ID is dummy)

<img width="963" alt="image" src="https://user-images.githubusercontent.com/13391129/170151126-6c512472-12dc-4bd3-8b09-a37d87a22e5c.png">
