### ISSUE TITLE
Option to show account name in top bar instead of account alias

### ISSUE THREAD

**Issue by bigwheel** [xhiroga/aws-peacock-management-console#24]
### Description

It would be great if top bar shows account name instead of account alias because account alias sometimes wouldn't be configured. Account name everytime exists.

### Use Case

When I didn't configured account alias.

### Proposed Solution

My coworker's proposal.

```javascript
decodeURIComponent(JSON.parse(decodeURIComponent(document.cookie.split(';').find(c => c.trim().startsWith('aws-userInfo')).split('=')[1])).issuer).match(/(?<=\().*?(?=\))/)[0]
```

This works only if we login through aws sso. Through IAM user login or root user login it doesn't work.

### Acknowledge

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by xhiroga** [comment]
Thank you for your feature request!

> It would be great if top bar shows account name instead of account alias because account alias sometimes wouldn't be configured. Account name everytime exists.

I totally agree to the motivation.

> My coworker's proposal.

Thank you for the proposal, but in some condition it is not enough.
When the user switched role beyond account from AWS SSO logged in user, the parameter does not change.

As alternative proposal, scraping from AWS SSO screen will work. This chrome extension do like so.
https://github.com/yaggytter/chrome-extension-awssso
