### ISSUE TITLE
Forefox version

### ISSUE THREAD

**Issue by takkyun** [xhiroga/aws-peacock-management-console#26]
### Description

Wanted Firefox version!

### Use Case

I am using Firefox as a developer. 

### Proposed Solution

Port it for Firefox addon.

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
@takkyun Thank you for reporting issue! Now firefox version is available.
https://addons.mozilla.org/en-US/firefox/addon/aws-peacock-management-console/

**Comment by xhiroga** [comment]
@takkyun Thank you for reporting issue! Now firefox version is available.
https://addons.mozilla.org/en-US/firefox/addon/aws-peacock-management-console/
