### ISSUE TITLE
Firefox Add-on?

### ISSUE THREAD

**Issue by raghuvv** [xhiroga/aws-peacock-management-console#48]
### Description

Can this be also ported to work as a Firefox add-on?

Can it somehow take advantage of the containers feature in firefox?

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
Hi @raghuvv, thank you for your issue!
Actually, Firefox add-on is already available.
https://addons.mozilla.org/ja/firefox/addon/aws-peacock-management-console/

**Comment by raghuvv** [comment]
Thanks for adding the link to README - sorry I assumed there was no Firefox add-on
