### ISSUE TITLE
Color picker & live preview in Config page

### ISSUE THREAD

**Issue by raghuvv** [xhiroga/aws-peacock-management-console#50]
### Description

provide a color picker in config page so users can pick a color visually

display of a live preview of chosen colors on a small mockup of AWS navigation and account menu would be even great 

### Acknowledge

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
Thank you for your request!
In future, this feature will be enable to import config from remote. No rich GUI editor feature is intentioned.
https://github.com/xhiroga/aws-peacock-management-console/issues/44
