### ISSUE TITLE
I want to be able to switch to a role on the console and still have it work

### ISSUE THREAD

**Issue by j13158mk** [xhiroga/aws-peacock-management-console#67]
### Description

![image](https://github.com/xhiroga/aws-peacock-management-console/assets/19896624/33f5711b-05b3-40e8-a9ca-46e37b8cf731)

It works when accessing via SSO, but not when switching roles from the menu in the upper right corner of the management console.

### Motivation

Same as above.

I know how to deal with it.
If you like, I can address it and submit a pull request.

### Acknowledge

- [X] This feature request is based on actual problems that have occurred after using the extension in YOUR practice.
- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
@j13158mk

Thank you for your report! I apologize for not noticing the issue myself as I haven't been using the role recently. Pull requests are very welcome and will definitely be reviewed. If I end up making the fix myself, it may take a little while. Thank you for your prompt response!
---
起票ありがとうございます！私自身がロールを最近使っていないため、問題に気づけず申し訳ありません。 PRは大歓迎ですし、必ずレビューします。私が修正する場合、少しお時間がかかりそうです。取り急ぎお返事させていただきました！

**Comment by j13158mk** [comment]
ありがとうございます。
今後対応を予定しますので、その際は確認お願いします。

**Comment by xhiroga** [comment]
@j13158mk さん、こんにちは。
Issueを修正してみました！（ https://github.com/xhiroga/aws-peacock-management-console/pull/75 ）

よければお試しください。ストアの評価もしていただけると嬉しいです😊
Issueの方はいったんクローズしますが、なにか問題があれば教えて下さいませ🙏

**Comment by j13158mk** [comment]
気づくのが遅くなりました。
ご対応ありがとうございます。
アイデアはあったのですが手が回らずでした。。
ストアも評価入れました。

**Comment by xhiroga** [comment]
@j13158mk いえいえ！お返事ありがとうございます。今後ともよろしくお願いいたします～！
