### ISSUE TITLE
No alias / account name shown, when using AWS IAM Identity Center

### ISSUE THREAD

**Issue by ash-hannigan** [xhiroga/aws-peacock-management-console#76]
### What is the problem?

The account alias or account number isn't being displayed. All I'm getting is role/username.
Colors and styles work great!

### Reproduction Steps

Setup IAM Identity Center, with password access for users.
Connect to account through account access page.

Account formatting is detected, but alias or name is shown.

Let me know what information you need to diagnose and I will be happy to provide.

### Browser Name

Edge

### Browser Version

121.0.2277.128

**Comment by ash-hannigan** [comment]
I just loaded in Chrome, and it works perfectly.
It's definitely an Edge specific bug, even though it allows loading of chrome store extensions, I understand that it's not currently a supported platform.
Would still be happy to help provide more information if you are willing to look into it?

**Comment by xhiroga** [comment]
Thank you for using and reporting!

I attempted to reproduce the issue in Edge, but it seems to be working on my end. Hmm.

If @ash-hannigan would like to use Edge in the future, please verify if accountNameList is being retrieved.

[Here's the link](https://github.com/xhiroga/aws-peacock-management-console/blob/c19321259acf616d83922a08c3412d041ba902a8/src/content.ts#L322) to the code.

As for the verification method, I'm sorry, but you'll need to add console.log statements yourself and rebuild...



![image](https://github.com/xhiroga/aws-peacock-management-console/assets/13391129/84991b2f-c884-44d5-8938-4d6a6e258737)

**Comment by ash-hannigan** [comment]
Thanks for responding so quickly.
I don't know what it was, but it's working as expected now...
