### ISSUE TITLE
account name is not shown without mouse over

### ISSUE THREAD

**Issue by filipemarques87** [xhiroga/aws-peacock-management-console#79]
### What is the problem?

The current alias is not being shown, however, if I put the mouse over the button, I can see the alias.
It seems to be the same issue described in https://github.com/xhiroga/aws-peacock-management-console/issues/76
The colors are working

### Reproduction Steps

Setup iam identity center and the configuration of aws-peacock-management plugin

### Browser Name

Chrome

### Browser Version

Version 126.0.6478.116 (Official Build) (64-bit)

### Other information

![image](https://github.com/xhiroga/aws-peacock-management-console/assets/32367633/52cfde9f-a3bb-4282-81ad-1e0ec4cb0750)

**Comment by xhiroga** [comment]
@filipemarques87 Hi, thank you for reporting your issue!

I guess its spec of AWS management console. It just shows title attribute of span.

![image](https://github.com/xhiroga/aws-peacock-management-console/assets/13391129/833777e7-7226-4ff3-80e4-44b18a9b8cdc)

I think this spec is rational, but if you feel any problem, please share it :)

**Comment by xhiroga** [comment]
Hi @filipemarques87,
I have fixed this bug in [version 2.12](https://chromewebstore.google.com/detail/aws-peacock-management-co/bknjjajglapfhbdcfgmhgkgfomkkaidj). Could you please try it out and let us know if it works as expected😀?

**Comment by filipemarques87** [comment]
Hi @xhiroga 
Yes, it is working. Thanks a lot :)
