### ISSUE TITLE
feat: add support for google cloud

### ISSUE THREAD

**Issue by juarezr** [xhiroga/aws-peacock-management-console#91]
## Google Cloud support

Adding support for Google Cloud will make the people working on multi-cloud scenarios happy.

Inspiration: This [ext](https://github.com/xhiroga/aws-peacock-management-console/issues).

### Motivation

- Multi-cloud configuration in just one extension and just one config.
- This wonderful extension deserves to have a port for other clouds.

### Sign in Method

- [ ] Direct login to target account via AWS SSO
- [ ] Direct login to target account via IAM user
- [ ] Login to a jump account via AWS SSO, then switch role to target account
- [ ] Login to a jump account via IAM user, then switch role to target account
- [ ] Sign in as the root user

### Acknowledge

- [X] This feature request is based on actual problems that have occurred after using the extension in YOUR practice.
- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by xhiroga** [comment]
Thank you for make issue, @juarezr san!

Do you think there is demand for an extension that would support an additional layer of UI for any cloud? I would consider teaming the development of such an new extension if the demand is strong, as it would require more resources to develop.

However, even in that case, it would be better to build it separately from this extension, as I think it needs to be simple enough that anyone can check all the sources if they want to, for use on a site like AWS, which needs to be secure☺️

**Comment by juarezr** [comment]
Hi, @xhiroga,

My perception is that :

- A significant portion of the people using this extension currently support/work in multiple clouds.
- They use the same browser most of the time to access the cloud consoles.
- An all-in-one extension has the advantages of:
  - Installing it only once.
  - Managing configuration in a centralized manner.

**Comment by xhiroga** [comment]
@juarezr Thank you for your idea! It's sounds nice and I agree with such a multi cloud extension is convenient.
However, I have no plan to upgrade this extension to that. I close this issue, but I'm looking forward to see that in future.
